name: Makefile CI

env:
  DST: NoPhoneSpam_blacklist.txt


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: blacklist
        path: NoPhoneSpam_blacklist.txt
