name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make
      run: make DST=NoPhoneSpam_blacklist.txt

    - uses: actions/upload-artifact@v4
      with:
        name: blacklist
        path: NoPhoneSpam_blacklist.txt
